openapi: 3.0.0
servers:
  - url: ''
info:
  description: |- 
  version: 2.0.0
  title: ''
paths:
  '/event_types/{uuid}':
    parameters:
      - schema:
          type: string
        name: uuid
        in: path
        required: true
    get:
      summary: Get Event Type
      tags:
        - Event Types
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  resource:
                    $ref: '#/components/schemas/EventType'
                required:
                  - resource
              examples:
                Example:
                  value:
                    resource:
                      uri: 'https://api.calendly.com/event_types/AAAAAAAAAAAAAAAA'
                      name: 15 Minute Meeting
                      active: true
                      booking_method: instant
                      slug: acmesales
                      scheduling_url: 'https://calendly.com/acmesales'
                      duration: 30
                      kind: solo
                      pooling_type: round_robin
                      type: StandardEventType
                      kind_description: Round Robin
                      color: '#fff200'
                      created_at: '2019-01-02T03:04:05.678123Z'
                      updated_at: '2019-08-07T06:05:04.321123Z'
                      internal_note: Internal note
                      description_plain: 15 Minute Meeting
                      description_html: <p>15 Minute Meeting</p>
                      profile:
                        type: User
                        name: Tamara Jones
                        owner: 'https://api.calendly.com/users/AAAAAAAAAAAAAAAA'
                      secret: true
                      deleted_at: null
                      admin_managed: false
                      custom_questions:
                        - name: Company Name
                          type: string
                          position: 0
                          enabled: true
                          required: true
                          answer_choices: []
                          include_other: false
                        - name: What would you like to discuss?
                          type: text
                          position: 0
                          enabled: true
                          required: true
                          answer_choices: []
                          include_other: false
                        - name: Number of employees
                          answer_choices:
                            - '1'
                            - 2-10
                            - 11-20
                            - 20+
                          enabled: true
                          include_other: true
                          position: 2
                          required: false
                          type: single_select
                        - name: Multi-Select Question
                          answer_choices:
                            - Answer 1
                            - Answer 2
                            - Answer 3
                            - Answer 4
                          enabled: true
                          include_other: true
                          position: 2
                          required: false
                          type: multi_select
                        - name: Phone Number
                          type: phone_number
                          position: 0
                          enabled: true
                          required: true
                          answer_choices: []
                          include_other: false
        '400':
          $ref: '#/components/responses/INVALID_ARGUMENT'
        '401':
          $ref: '#/components/responses/UNAUTHENTICATED'
        '403':
          $ref: '#/components/responses/PERMISSION_DENIED'
        '404':
          $ref: '#/components/responses/NOT_FOUND'
        '500':
          $ref: '#/components/responses/UNKNOWN'
      operationId: get-event_types-uuid
      security:
        - oauth2: []
        - personal_access_token: []
      description: Returns information about a specified Event Type.
